# -*- coding: utf-8 -*-
"""阅读素材框架:16 大话题 × A1/A2/B1/B2 四级句子池。

结构约定:
- FACTS[i] = (en_tpl, zh_tpl, 问句tpl, 答案slot, 干扰bank):句子写进文章 ⇒ 该句自动成为一道细节题来源。
- FILLERS[i] = (en_tpl, zh_tpl):只铺陈,不出题。
- {kw1}/{kw2} 为话题关键词(各话题 kws 中抽取),英文已含冠词,模板直接裸用。
- B2 为议论文脚手架(INTRO/BODY/CONCLUSION + 话题论点句)。

话题清单前 8 个为测试卡口要求的“8 大场景”,必须保留。
"""

# 话题定义:key / 中文名 / 主旨gist(主旨题正确项) / vocab标签 / 关键词NP / 话题名词 / B2论点句 / 推断题 / 目的题
TOPICS = [
    dict(key="campus", topic="校园生活", gist="校园里的学习与课外活动",
         tags=["campus", "school", "study", "class"],
         kws=[("the school library", "学校图书馆"), ("the playground", "操场"), ("the classroom", "教室"),
              ("the school gate", "校门口"), ("the teachers' office", "老师办公室"), ("the school garden", "学校花园"),
              ("the reading room", "阅览室"), ("the science lab", "科学实验室")],
         noun=("school life", "校园生活"),
         thesis=[("School life is not only about classes, but also about friendship and growth.",
                  "校园生活不仅关乎上课,也关乎友谊与成长。"),
                 ("A good school gives students more than knowledge.",
                  "一所好学校给予学生的不只是知识。")],
         infer=("从文中可以推断出主角对校园生活的态度是?",
                "总体是积极喜欢的", ["觉得无聊想逃离", "非常讨厌同学", "毫不在意可有可无"]),
         purpose=("作者写这篇文章的主要目的是?", "分享自己的校园生活与感受",
                  ["推销一所学校", "批评学校的制度", "教读者数学知识"])),
    dict(key="work", topic="职场工作", gist="工作中的日常与职业成长",
         tags=["work", "workplace", "business", "job"],
         kws=[("the office", "办公室"), ("the meeting room", "会议室"), ("the front desk", "前台"),
              ("the coffee corner", "咖啡角"), ("the work station", "工位"), ("the training center", "培训中心"),
              ("the project plan", "项目计划"), ("the weekly report", "周报")],
         noun=("work life", "职场生活"),
         thesis=[("Doing a job well needs both skills and a willing heart.",
                  "做好一份工作既需要能力,也需要意愿。"),
                 ("Every small task at work is a step toward growth.",
                  "工作中的每一件小事都是成长的台阶。")],
         infer=("从文中可以推断出主角对工作的态度是?", "认真且愿意学习", ["敷衍应付", "打算马上辞职", "完全排斥合作"]),
         purpose=("作者写这篇文章的主要目的是?", "介绍自己的工作日常与体会",
                  ["招聘新员工", "抱怨加班严重", "讲解公司历史"])),
    dict(key="travel", topic="旅行出行", gist="一次出行的经历与见闻",
         tags=["travel", "transport", "holiday", "city"],
         kws=[("the train station", "火车站"), ("the airport", "机场"), ("the hotel", "酒店"),
              ("the old town", "老城区"), ("the night market", "夜市"), ("the ticket office", "售票处"),
              ("the bus stop", "公交车站"), ("the travel plan", "旅行计划")],
         noun=("travel", "旅行"),
         thesis=[("Travel teaches us things that no classroom can offer.",
                  "旅行教会我们课堂给不了的东西。"),
                 ("The best part of a trip is often the people we meet.",
                  "旅途中最美好的往往是遇到的人。")],
         infer=("从文中可以推断出这次旅行的整体感受是?", "愉快且值得", ["糟糕透顶", "平淡无奇毫无收获", "危险重重"]),
         purpose=("作者写这篇文章的主要目的是?", "记录一次旅行的经历", ["推销旅行社产品", "警告不要出门旅行", "介绍火车构造"])),
    dict(key="shopping", topic="购物消费", gist="一次购物经历与消费选择",
         tags=["shopping", "money", "clothes", "food"],
         kws=[("the shopping mall", "购物中心"), ("the supermarket", "超市"), ("the fruit shop", "水果店"),
              ("the book store", "书店"), ("the cashier", "收银台"), ("the discount area", "打折区"),
              ("the shopping list", "购物清单"), ("the online shop", "网店")],
         noun=("shopping", "购物"),
         thesis=[("Buying things wisely is a skill everyone needs to learn.",
                  "明智地消费是每个人都要学的技能。"),
                 ("The cheapest thing is not always the best choice.",
                  "最便宜的并不总是最好的选择。")],
         infer=("从文中可以推断出主角的消费观念是?", "理性、按需购买", ["看到就买毫不节制", "只买贵的", "完全不看价格也不比价"]),
         purpose=("作者写这篇文章的主要目的是?", "分享一次购物经历与心得",
                  ["宣传某品牌打折", "劝大家不要购物", "讲解收银系统原理"])),
    dict(key="health", topic="健康生活", gist="健康的生活习惯与运动",
         tags=["health", "body", "sport", "feeling"],
         kws=[("the gym", "健身房"), ("the running track", "跑道"), ("the park path", "公园小路"),
              ("the swimming pool", "游泳池"), ("the dining hall", "食堂"), ("the school clinic", "校医务室"),
              ("the health check", "体检"), ("the sleep schedule", "作息表")],
         noun=("a healthy life", "健康生活"),
         thesis=[("Health is built by small habits repeated every day.",
                  "健康是由每天重复的小习惯积累起来的。"),
                 ("Exercise is the cheapest medicine we can give ourselves.",
                  "锻炼是我们能给自己最便宜的药。")],
         infer=("从文中可以推断出主角的生活方式是?", "健康有规律", ["长期熬夜", "完全不吃早餐", "从不运动且饮食失控"]),
         purpose=("作者写这篇文章的主要目的是?", "倡导健康的生活方式", ["推销健身卡", "介绍疾病治疗方案", "吐槽医院排队"])),
    dict(key="social", topic="社交生活", gist="朋友交往与社交活动",
         tags=["social", "friend", "feeling", "party"],
         kws=[("the birthday party", "生日聚会"), ("the club room", "社团活动室"), ("the school hall", "学校礼堂"),
              ("the chat group", "聊天群"), ("the picnic ground", "野餐草地"), ("the game corner", "游戏角"),
              ("the volunteer team", "志愿者小队"), ("the class meeting", "班会")],
         noun=("friendship", "友谊与社交"),
         thesis=[("Real friendship grows slowly, like a tree.",
                  "真正的友谊像树一样慢慢生长。"),
                 ("Listening to others is the first step of making friends.",
                  "倾听他人是交朋友的第一步。")],
         infer=("从文中可以推断出主角与朋友的关系是?", "融洽互相支持", ["经常吵架", "十分疏远", "互相利用"]),
         purpose=("作者写这篇文章的主要目的是?", "讲述与朋友交往的点滴",
                  ["组织一场比赛", "教网络聊天技巧", "招募社团成员"])),
    dict(key="media", topic="媒体网络", gist="网络与数字生活的利与弊",
         tags=["internet", "media", "phone", "music"],
         kws=[("the study app", "学习应用"), ("the online class", "网课"), ("the video page", "视频页面"),
              ("the message box", "消息盒子"), ("the search page", "搜索页面"), ("the e-book shelf", "电子书架"),
              ("the screen-time report", "屏幕时间报告"), ("the school computer room", "学校机房")],
         noun=("life online", "网络生活"),
         thesis=[("The internet is a tool; whether it helps depends on how we use it.",
                  "互联网是工具,是否有益取决于我们怎么用。"),
                 ("Too much screen time quietly takes away our focus.",
                  "过多的屏幕时间正在悄悄偷走我们的专注力。")],
         infer=("从文中可以推断出作者对上网的态度是?", "合理使用就有益处", ["认为网络毫无用处", "主张整天上网", "从不接触任何网络"]),
         purpose=("作者写这篇文章的主要目的是?", "讨论网络使用的心得与平衡",
                  ["推广一款新应用", "教人搭建网站", "批评所有短视频"])),
    dict(key="service", topic="生活服务", gist="日常生活中获得的服务与帮助",
         tags=["city", "home", "transport", "bank"],
         kws=[("the community center", "社区中心"), ("the post office", "邮局"), ("the repair shop", "修理店"),
              ("the bank counter", "银行柜台"), ("the bus card machine", "公交刷卡机"), ("the library desk", "图书馆服务台"),
              ("the hospital guide", "医院导诊台"), ("the neighborhood station", "小区服务站")],
         noun=("everyday services", "日常生活服务"),
         thesis=[("Small services around us make city life smooth and warm.",
                  "身边的小服务让城市生活顺畅而温暖。"),
                 ("Asking for help in the right place saves a lot of time.",
                  "在对的地方寻求帮助能省很多时间。")],
         infer=("从文中可以推断出主角对这些服务的评价是?", "方便且有帮助", ["又贵又难用", "完全没必要存在", "态度恶劣效率低"]),
         purpose=("作者写这篇文章的主要目的是?", "记录使用生活服务的经历",
                  ["投诉某个部门", "做服务价格对比广告", "介绍城市历史"])),
    dict(key="family", topic="家庭生活", gist="家里的日常与亲情",
         tags=["family", "home", "food", "cooking"],
         kws=[("the kitchen", "厨房"), ("the living room", "客厅"), ("the family dinner", "家庭晚餐"),
              ("the balcony", "阳台"), ("the old photo album", "旧相册"), ("the family chat", "家庭群聊"),
              ("the weekend breakfast", "周末早餐"), ("the study room", "书房")],
         noun=("family life", "家庭生活"),
         thesis=[("Home is where we learn to love and to share.",
                  "家是我们学会爱与分享的地方。"),
                 ("A family that eats together stays close.",
                  "常一起吃饭的家庭感情更深。")],
         infer=("从文中可以推断出主角的家庭氛围是?", "温暖和睦", ["冷漠疏远", "经常争吵", "各忙各的互不关心"]),
         purpose=("作者写这篇文章的主要目的是?", "描写家庭生活的温暖",
                  ["抱怨家务太多", "出租房屋", "介绍家族企业"])),
    dict(key="food", topic="美食烹饪", gist="食物与烹饪的乐趣",
         tags=["food", "cooking", "drink"],
         kws=[("the kitchen table", "餐桌"), ("the night snack bar", "夜宵摊"), ("the noodle shop", "面馆"),
              ("the bakery", "面包店"), ("the vegetable market", "菜市场"), ("the tea house", "茶馆"),
              ("the family kitchen", "家里的小厨房"), ("the food festival", "美食节")],
         noun=("food and cooking", "美食与烹饪"),
         thesis=[("Cooking for others is a quiet way of saying I care.",
                  "为别人下厨是表达关心的安静方式。"),
                 ("Every family has a dish that tells its story.",
                  "每个家庭都有一道能讲出身世的菜。")],
         infer=("从文中可以推断出主角对烹饪的态度是?", "热爱并乐在其中", ["觉得麻烦讨厌", "只点外卖从不做", "被迫应付"]),
         purpose=("作者写这篇文章的主要目的是?", "分享烹饪与美食体验",
                  ["推荐减肥食谱", "推销厨具", "讲解营养学理论"])),
    dict(key="sport", topic="运动健身", gist="运动锻炼的经历与收获",
         tags=["sport", "health", "competition"],
         kws=[("the basketball court", "篮球场"), ("the swimming pool", "游泳池"), ("the morning playground", "清晨的操场"),
              ("the bike lane", "自行车道"), ("the climbing wall", "攀岩墙"), ("the ping-pong room", "乒乓球室"),
              ("the school sports day", "校运动会"), ("the yoga class", "瑜伽课")],
         noun=("sports and exercise", "运动与锻炼"),
         thesis=[("Sports teach us to lose today and win tomorrow.",
                  "运动教会我们今天输、明天赢。"),
                 ("The hardest step in exercise is the one out of the door.",
                  "锻炼中最难的一步是迈出家门的那一步。")],
         infer=("从文中可以推断出运动给主角带来了什么?", "更好的状态与自信", ["严重的伤病", "成绩明显下滑", "与朋友的矛盾"]),
         purpose=("作者写这篇文章的主要目的是?", "分享运动经历与收获",
                  ["售卖健身课程", "报道职业联赛", "讲解人体肌肉结构"])),
    dict(key="nature", topic="自然环境", gist="亲近自然的观察与感受",
         tags=["nature", "weather", "animal", "plant", "season"],
         kws=[("the city park", "城市公园"), ("the river bank", "河岸"), ("the green hill", "青山"),
              ("the plant garden", "植物园"), ("the bird-watching spot", "观鸟点"), ("the forest path", "林间小路"),
              ("the flower market", "花市"), ("the camping site", "露营营地")],
         noun=("nature", "自然"),
         thesis=[("Nature never hurries, yet everything gets done.",
                  "自然从不匆忙,却样样成事。"),
                 ("Watching a sunset costs nothing but gives us peace.",
                  "看日落不花一分钱,却给我们宁静。")],
         infer=("从文中可以推断出作者对自然的态度是?", "热爱并心存敬畏", ["觉得无聊", "害怕回避", "只想开发利用"]),
         purpose=("作者写这篇文章的主要目的是?", "抒发对自然的观察与热爱",
                  ["推销露营装备", "讲解地理知识考点", "批评城市绿化"])),
    dict(key="city", topic="城市生活", gist="城市里的生活见闻",
         tags=["city", "transport", "shopping", "community"],
         kws=[("the subway station", "地铁站"), ("the city square", "城市广场"), ("the corner store", "街角小店"),
              ("the pedestrian street", "步行街"), ("the bus terminal", "公交枢纽"), ("the city library", "市图书馆"),
              ("the riverside walk", "滨江步道"), ("the night view spot", "夜景观赏点")],
         noun=("city life", "城市生活"),
         thesis=[("A city is alive because of the people in its streets.",
                  "城市因街巷里的人而鲜活。"),
                 ("Living in a city means learning to share space with others.",
                  "住在城市意味着学会与他人共享空间。")],
         infer=("从文中可以推断出作者对城市生活的感受是?", "便利且多彩", ["拥挤到无法忍受", "孤独冷漠", "危险到不敢出门"]),
         purpose=("作者写这篇文章的主要目的是?", "记录城市生活的观察",
                  ["做城市落户广告", "统计人口数据", "介绍地铁施工技术"])),
    dict(key="hobby", topic="兴趣爱好", gist="培养兴趣爱好的经历",
         tags=["hobby", "music", "art", "reading"],
         kws=[("the piano room", "琴房"), ("the art classroom", "美术教室"), ("the chess corner", "棋角"),
              ("the photo club", "摄影社"), ("the model workbench", "模型工作台"), ("the dance studio", "舞蹈房"),
              ("the guitar case", "吉他包"), ("the story-writing desk", "写故事的桌子")],
         noun=("hobbies", "兴趣爱好"),
         thesis=[("A hobby is a friend that never gets bored of you.",
                  "爱好是一个永远不会嫌你烦的朋友。"),
                 ("We work to live, and we live for what we love doing.",
                  "我们为生活而工作,为热爱的事而生活。")],
         infer=("从文中可以推断出兴趣爱好对主角的意义是?", "带来快乐与坚持", ["只是消磨时间", "加重了负担", "跟风装样子"]),
         purpose=("作者写这篇文章的主要目的是?", "分享培养爱好的经历",
                  ["招收兴趣班学员", "拍卖手工作品", "比较乐器价格"])),
    dict(key="festival", topic="节日文化", gist="节日里的传统与庆祝",
         tags=["holiday", "festival", "family", "food"],
         kws=[("the family dinner table", "团圆饭桌"), ("the lantern street", "灯笼街"), ("the spring market", "年货市场"),
              ("the gift box", "礼物盒"), ("the temple fair", "庙会"), ("the moon-lit yard", "月光小院"),
              ("the dragon boat river", "赛龙舟的河边"), ("the holiday plan", "假期计划")],
         noun=("festivals", "节日"),
         thesis=[("Festivals are the memory of a family and a culture.",
                  "节日是一个家庭和一种文化的记忆。"),
                 ("Traditions change their form, but love stays the same.",
                  "传统的形式会变,但爱始终如一。")],
         infer=("从文中可以推断出作者对传统节日的感情是?", "珍视并乐于参与", ["觉得过时麻烦", "无所谓不关心", "更喜欢外来节日"]),
         purpose=("作者写这篇文章的主要目的是?", "描写节日习俗与团聚",
                  ["促销节日礼品", "考证节日起源学术", "批评放假安排"])),
    dict(key="science", topic="科学技术", gist="科学新知与技术的启发",
         tags=["science", "internet", "study"],
         kws=[("the science museum", "科技馆"), ("the robot show", "机器人展"), ("the planetarium hall", "天文馆大厅"),
              ("the school lab", "学校实验室"), ("the science corner", "科学角"), ("the telescope", "望远镜"),
              ("the coding club", "编程社"), ("the nature documentary", "自然纪录片")],
         noun=("science and technology", "科学与技术"),
         thesis=[("Science starts from a simple question asked honestly.",
                  "科学始于一个诚实提出的小问题。"),
                 ("Technology changes tools, but curiosity drives it all.",
                  "技术改变工具,而好奇心驱动一切。")],
         infer=("从文中可以推断出作者对科学的态度是?", "好奇并乐于探索", ["觉得遥不可及", "认为无用", "盲目崇拜"]),
         purpose=("作者写这篇文章的主要目的是?", "分享一次科学探索的见闻",
                  ["发布科研成果", "售卖科技产品", "讲解考试考点"])),
]

# 8 大场景(测试卡口)在前 8 个话题
CANONICAL_TOPICS = [t["topic"] for t in TOPICS[:8]]

# ---------- A1:事实句池(句即题源)+ 铺陈句池 ----------

A1_FACTS = [
    ("{name} likes {sport} very much.", "{name_zh}非常喜欢{sport_zh}。", "{name_zh}喜欢什么?", "sport", "sport"),
    ("{name} usually eats {food} for lunch.", "{name_zh}午饭通常吃{food_zh}。", "{name_zh}午饭通常吃什么?", "food", "food"),
    ("{name} goes to {place} on {weekday}.", "{name_zh}{weekday_zh}会去{place_zh}。", "{name_zh}{weekday_zh}去哪里?", "place", "place"),
    ("{name}'s favorite subject is {subject}.", "{name_zh}最喜欢的科目是{subject_zh}。", "{name_zh}最喜欢的科目是什么?", "subject", "subject"),
    ("{name} wants to visit {city}.", "{name_zh}想去{city_zh}旅行。", "{name_zh}想去哪个城市旅行?", "city", "city"),
    ("{name} drinks {drink} every morning.", "{name_zh}每天早上喝{drink_zh}。", "{name_zh}每天早上喝什么?", "drink", "drink"),
    ("{name} wears {clothes} today.", "{name_zh}今天穿着{clothes_zh}。", "{name_zh}今天穿着什么?", "clothes", "clothes"),
    ("{name}'s favorite season is {season}.", "{name_zh}最喜欢的季节是{season_zh}。", "{name_zh}最喜欢的季节是什么?", "season", "season"),
]

A1_FILLERS = [
    ("My friend {friend} is very kind.", "我的朋友{friend_zh}很善良。"),
    ("We often go to {place} together.", "我们经常一起去{place_zh}。"),
    ("{kw1} is not far from my home.", "{kw1_zh}离我家不远。"),
    ("{kw1} is my favorite place.", "{kw1_zh}是我最喜欢的地方。"),
    ("I am happy every day.", "我每天都开心。"),
    ("{friend} likes {food} too.", "{friend_zh}也喜欢{food_zh}。"),
    ("We talk about {subject} a lot.", "我们经常谈论{subject_zh}。"),
    ("After school, we play together.", "放学后我们一起玩。"),
    ("{kw2} is big and clean.", "{kw2_zh}又大又干净。"),
    ("I like my life very much.", "我非常喜欢我的生活。"),
    ("{name} and {friend} are in the same class.", "{name_zh}和{friend_zh}在同一个班。"),
    ("{friend} often helps me with {subject}.", "{friend_zh}经常帮我学{subject_zh}。"),
]

# ---------- A2 ----------

A2_FACTS = [
    ("{name} plays {sport} with {friend} every {weekday}.", "{name_zh}每{weekday_zh}和{friend_zh}一起打{sport_zh}。",
     "{name_zh}每{weekday_zh}和谁一起打{sport_zh}?", "friend", "name"),
    ("{name} usually has {food} for breakfast.", "{name_zh}早餐通常吃{food_zh}。", "{name_zh}早餐通常吃什么?", "food", "food"),
    ("{name} borrowed a book about {subject} from {place}.", "{name_zh}从{place_zh}借了一本关于{subject_zh}的书。",
     "{name_zh}从哪里借了一本关于{subject_zh}的书?", "place", "place"),
    ("{name} is going to travel to {city} in {month}.", "{name_zh}打算{month_zh}去{city_zh}旅行。",
     "{name_zh}打算几月去{city_zh}旅行?", "month", "month"),
    ("{name} wants to be a {job} in the future.", "{name_zh}将来想当{job_zh}。", "{name_zh}将来想做什么工作?", "job", "job"),
    ("{name} likes {weather} days best.", "{name_zh}最喜欢{weather_zh}的日子。", "{name_zh}最喜欢什么样的天气?", "weather", "weather"),
    ("{name}'s favorite animal is the {animal}.", "{name_zh}最喜欢的动物是{animal_zh}。", "{name_zh}最喜欢的动物是什么?", "animal", "animal"),
    ("{name} spent the weekend at {place}.", "{name_zh}周末在{place_zh}度过。", "{name_zh}周末在哪里度过?", "place", "place"),
    ("{name} drinks {drink} after doing sports.", "{name_zh}运动后喝{drink_zh}。", "{name_zh}运动后喝什么?", "drink", "drink"),
    ("{friend}'s birthday is in {month}.", "{friend_zh}的生日在{month_zh}。", "{friend_zh}的生日在哪个月?", "month", "month"),
    ("{name} is reading a book about {subject}.", "{name_zh}正在读一本关于{subject_zh}的书。", "{name_zh}正在读关于什么的书?", "subject", "subject"),
    ("{name} bought {clothes} at the shop yesterday.", "{name_zh}昨天在商店买了{clothes_zh}。", "{name_zh}昨天在商店买了什么?", "clothes", "clothes"),
]

A2_FILLERS = [
    ("Last {weekday}, {name} and {friend} went to {kw1}.", "上{weekday_zh},{name_zh}和{friend_zh}去了{kw1_zh}。"),
    ("{kw1} is one of the best places in the city.", "{kw1_zh}是这个城市最好的地方之一。"),
    ("There are always many people at {kw2}.", "{kw2_zh}总是有很多人。"),
    ("{name} thinks {subject} is interesting but a little difficult.", "{name_zh}觉得{subject_zh}有趣但有点难。"),
    ("{friend} is interested in {hobby}.", "{friend_zh}对{hobby_zh}很感兴趣。"),
    ("The weather was {weather} that day.", "那天天气是{weather_zh}。"),
    ("{name} learned a lot about {subject}.", "{name_zh}学到了很多关于{subject_zh}的知识。"),
    ("Both of them like {food} and {drink}.", "他们俩都喜欢{food_zh}和{drink_zh}。"),
    ("{name} hopes to visit {city} one day.", "{name_zh}希望有一天去{city_zh}。"),
    ("It takes twenty minutes to get to {kw1} by bike.", "骑自行车到{kw1_zh}要二十分钟。"),
    ("{name} and {friend} had great fun there.", "{name_zh}和{friend_zh}在那里玩得很开心。"),
    ("They took many photos at {kw2}.", "他们在{kw2_zh}拍了很多照片。"),
    ("{name} wrote about the day in the diary.", "{name_zh}在日记里写下了这一天。"),
    ("Life is full of small surprises.", "生活充满了小小的惊喜。"),
]

# ---------- B1 ----------

B1_FACTS = [
    ("{name} has practiced {sport} for three years and won a prize last term.",
     "{name_zh}练习{sport_zh}已经三年,上学期还获了奖。", "{name_zh}练习了三年并获奖的项目是什么?", "sport", "sport"),
    ("{name} usually spends the weekend reading at {place}.",
     "{name_zh}通常周末在{place_zh}阅读。", "{name_zh}通常周末在哪里阅读?", "place", "place"),
    ("{friend} advised {name} to try {hobby} as a new hobby.",
     "{friend_zh}建议{name_zh}尝试{hobby_zh}作为新爱好。", "{friend_zh}建议{name_zh}尝试什么新爱好?", "hobby", "hobby"),
    ("{name} is saving money to buy a ticket to {city}.",
     "{name_zh}正在攒钱买去{city_zh}的车票。", "{name_zh}攒钱想去哪座城市?", "city", "city"),
    ("{name} plans to study {subject} harder this term.",
     "{name_zh}这学期打算更努力地学{subject_zh}。", "{name_zh}这学期打算更努力学哪一科?", "subject", "subject"),
    ("{name} ordered {food} and {drink} at {kw1} last night.",
     "{name_zh}昨晚在{kw1_zh}点了{food_zh}和{drink_zh}。", "{name_zh}昨晚在{kw1_zh}点了什么吃的?", "food", "food"),
    ("{name}'s dream job is to be a {job}.",
     "{name_zh}梦想的工作是当{job_zh}。", "{name_zh}梦想的工作是什么?", "job", "job"),
    ("{name} will take part in a {sport} match in {month}.",
     "{name_zh}{month_zh}将参加一场{sport_zh}比赛。", "{name_zh}几月参加{sport_zh}比赛?", "month", "month"),
    ("{friend} and {name} are preparing a report about {kw2}.",
     "{friend_zh}和{name_zh}正在准备一份关于{kw2_zh}的报告。", "谁和{name_zh}一起准备报告?", "friend", "name"),
    ("{name} prefers {weather} weather when running in {place}.",
     "{name_zh}在{place_zh}跑步时更喜欢{weather_zh}的天气。", "{name_zh}跑步时更喜欢什么天气?", "weather", "weather"),
    ("{name} keeps a small {animal} at home and feeds it every morning.",
     "{name_zh}在家里养了一只小{animal_zh},每天早上喂它。", "{name_zh}在家养了什么小动物?", "animal", "animal"),
    ("{name} bought {clothes} online because it was much cheaper.",
     "{name_zh}网购了{clothes_zh},因为便宜得多。", "{name_zh}在网上买了什么?", "clothes", "clothes"),
]

B1_FILLERS = [
    ("{kw1} has become an important part of daily life.", "{kw1_zh}已经成为日常生活的重要部分。"),
    ("People around {name} often share different ideas about {kw2}.", "{name_zh}身边的人经常分享对{kw2_zh}的不同看法。"),
    ("At first, {name} found it difficult to keep the habit.", "起初,{name_zh}觉得很难坚持这个习惯。"),
    ("Little by little, things began to change.", "一点一点地,情况开始改变。"),
    ("{friend} always says that small steps matter more than big plans.",
     "{friend_zh}总说小步前进比宏大计划更重要。"),
    ("On {weekday} evenings, {name} reviews the notes from class.", "{weekday_zh}晚上,{name_zh}会复习课堂笔记。"),
    ("They talked about everything from schoolwork to future dreams.", "他们无话不谈,从功课聊到未来的梦想。"),
    ("{name} believes that trying new things keeps life fresh.", "{name_zh}相信尝试新事物让生活保持新鲜。"),
    ("There is still a long way to go, but the direction is right.", "路还很长,但方向是对的。"),
    ("There are always more possibilities than we expect.", "可能性永远比我们预期的多。"),
    ("{kw2} looked quieter than usual that evening.", "那天傍晚,{kw2_zh}看起来比平时更安静。"),
    ("{name} wrote down every idea in a small notebook.", "{name_zh}把每个想法都记在一个小本子上。"),
    ("Sometimes a short talk can solve a big problem.", "有时一次简短的谈话能解决一个大问题。"),
    ("What matters most is not speed, but keeping on.", "最重要的不是速度,而是坚持。"),
    ("{name} thanked {friend} for the honest advice.", "{name_zh}感谢{friend_zh}真诚的建议。"),
    ("The experience taught {name} more than any book could.", "这段经历教给{name_zh}的比任何书都多。"),
]

# ---------- B2 议论文脚手架 ----------

B2_INTRO = [
    ("People often talk about {kw1} these days, and opinions are far from the same.",
     "如今人们经常谈论{kw1_zh},看法却大相径庭。"),
    ("{topic_noun} may sound like a small thing, yet it shapes our days in quiet ways.",
     "{topic_noun_zh}听起来也许是小事,却在悄然塑造我们的每一天。"),
    ("When it comes to {topic_noun}, everyone seems to have a story to tell.",
     "说起{topic_noun_zh},每个人似乎都有故事可讲。"),
    ("Few topics touch daily life as closely as {topic_noun} does.",
     "很少有话题像{topic_noun_zh}这样贴近日常生活。"),
]

B2_BODY = [
    ("To begin with, a clear example comes from everyday experience.", "首先,一个清晰的例子来自日常经验。"),
    ("At {kw1}, for instance, small details often decide the final result.",
     "比如在{kw1_zh},细节往往决定最终结果。"),
    ("What happens at {kw2} tells a similar story.", "{kw2_zh}发生的事情讲述了类似的道理。"),
    ("Some people argue that habits matter more than talent.", "有人认为习惯比天赋更重要。"),
    ("Others believe that the environment shapes almost everything.", "另一些人则认为环境几乎决定一切。"),
    ("In fact, the two ideas are not opposites but partners.", "事实上,这两种观点并非对立,而是相辅相成。"),
    ("Research and daily observation point to the same direction.", "研究和日常观察都指向同一个方向。"),
    ("A short interview with people around us makes the point clearer.", "对我们身边人的简短采访能让观点更清晰。"),
    ("Consider how differently people spend a single free evening.", "想想人们度过一个空闲夜晚的方式有多不同。"),
    ("The difference rarely comes from money alone.", "这种差异很少仅仅来自金钱。"),
    ("More often, it comes from attitude and small daily choices.", "更多时候,它来自态度和日常的小选择。"),
    ("Critics may say that change takes too long to be worth trying.", "批评者可能说改变太久,不值得尝试。"),
    ("Yet even a slow change is better than a comfortable standstill.", "然而即便是缓慢的改变也好过安逸的停滞。"),
    ("History offers plenty of examples of patient progress.", "历史提供了许多耐心积累进步的例子。"),
    ("Of course, balance is necessary rather than blind effort.", "当然,需要的是平衡,而非盲目用力。"),
    ("Parents, schools and society all play a part in the process.", "父母、学校与社会都在其中发挥作用。"),
    ("When these forces work together, the result is usually surprising.", "当这些力量协同,结果往往出人意料。"),
    ("It is also worth noticing the cost of doing nothing.", "同样值得注意的是不作为的代价。"),
    ("Problems ignored today simply return with interest tomorrow.", "今天被忽视的问题明天只会变本加厉地回来。"),
    ("By comparison, early action is almost always cheaper.", "相比之下,早期行动几乎总是代价更低。"),
    ("There is a lesson here for every one of us.", "这里对我们每个人都有启示。"),
    ("The point is not to be perfect, but to keep moving.", "关键不在于完美,而在于持续前行。"),
]

# B2 细节题源(题号 fact)
B2_FACTS = [
    ("The writer once spent a whole {season} practicing near {kw1}.",
     "作者曾花了一整个{season_zh}在{kw1_zh}附近练习。", "作者曾花了一整个什么季节练习?", "season", "season"),
    ("In the writer's family, {food} is the dish that appears every weekend.",
     "在作者家里,{food_zh}是每个周末都会出现的菜。", "在作者家里,每个周末都会出现什么菜?", "food", "food"),
    ("When the writer needs to think, the first choice is always {place}.",
     "当作者需要思考时,第一选择总是{place_zh}。", "作者需要思考时首先去哪里?", "place", "place"),
]

B2_CONCLUSION = [
    ("In short, {topic_noun} is a mirror that reflects how we live.", "总之,{topic_noun_zh}是一面映照我们如何生活的镜子。"),
    ("To conclude, small steady steps in {topic_noun} beat grand but empty plans.",
     "结语:{topic_noun_zh}中坚实的小步胜过宏大而空洞的计划。"),
    ("All in all, the way we treat {topic_noun} quietly decides the way we grow.",
     "归根结底,我们对待{topic_noun_zh}的方式悄然决定了我们成长的方式。"),
    ("In one word, a thoughtful attitude toward {topic_noun} is worth more than any shortcut.",
     "一言以蔽之,对待{topic_noun_zh}的认真态度胜过任何捷径。"),
]

B2_PURPOSE_Q = ("作者写这篇议论文的主要目的是?", "就话题表达观点并给出建议",
                ["讲述一个恐怖故事", "推销一种商品", "记叙一次考试经历"])

# 生成参数(每级文章的段落数/段内句数/嵌入 vocab 句数)
READING_LAYOUT = {
    "A1": dict(paras=3, frame_sents=3, embeds=2, facts=2, questions=4),
    "A2": dict(paras=4, frame_sents=3, embeds=3, facts=3, questions=5),
    "B1": dict(paras=5, frame_sents=3, embeds=4, facts=3, questions=6),
    "B2": dict(paras=12, frame_sents=2, embeds=30, facts=1, questions=8),
}
